Repository Guakamoli/denostr, pull requests merged in 2023-03, with the labels that each got.

#21 chore: modify name of inspector
  .github/workflows/pr-title-checker.yml
Labels: chore

#22 chore: add job name of inspector
  .github/workflows/pr-title-checker.yml
Labels: chore

#24 chore: making changes to deployment files
  deployment/maintenance.yml
  deployment/static-mirroring.yml
  deployment/worker.yml
Labels: chore

#25 chore: 更新 Denostr 产品描述
  README.md
Labels: chore

#27 ci: eliminate mandatory `commit-lint` rule
  .github/workflows/checks.yml
  docs/apply-for-k8s.md
  docs/apply-for-k8s_zhCN.md
Labels: ci

#28 fix: in-memory cache eviction time not updated
  deployment/worker.yaml
  docs/apply-for-k8s.md
  docs/apply-for-k8s_zhCN.md
  src/@types/adapters.ts
  src/adapters/inmemory-cache-adapter.ts
  src/factories/rate-limiter-factory.ts
  src/utils/sliding-window-rate-limiter.ts
  test/unit/cache/inmemory-cache-adapter.test.ts
Labels: fix
